from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QComboBox,
    QFrame,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPushButton,
    QRadioButton,
    QScrollArea,
    QSlider,
    QVBoxLayout,
    QWidget,
)

from blink_call.widget import HDividerLine


class BlinkCallPage:
    def __init__(self, content_stack):
        scroll = QScrollArea()
        scroll.setObjectName("settingRightScroll")
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        content_stack.addWidget(scroll)

        page = QFrame()
        page.setObjectName("settingContentPage")
        page.setMinimumWidth(700)
        scroll.setWidget(page)

        layout = QVBoxLayout(page)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(16)

        self.switch_row = QWidget()
        switch_layout = QHBoxLayout(self.switch_row)
        switch_layout.setContentsMargins(0, 0, 0, 0)
        switch_layout.setSpacing(16)
        self.switch_label = QLabel("Enable blink call")
        self.switch_label.setObjectName("settingSubSectionTitle")
        self.enabled_radio = QRadioButton("On")
        self.disabled_radio = QRadioButton("Off")
        switch_layout.addWidget(self.switch_label)
        switch_layout.addStretch()
        switch_layout.addWidget(self.enabled_radio)
        switch_layout.addWidget(self.disabled_radio)
        layout.addWidget(self.switch_row)

        self.switch_divider = HDividerLine()
        layout.addWidget(self.switch_divider)

        self.progress_row = QWidget()
        progress_layout = QHBoxLayout(self.progress_row)
        progress_layout.setContentsMargins(0, 0, 0, 0)
        progress_layout.setSpacing(16)
        self.progress_label = QLabel("Show top progress bar on home page")
        self.progress_label.setObjectName("settingSubSectionTitle")
        self.progress_show_radio = QRadioButton("Show")
        self.progress_hide_radio = QRadioButton("Hide")
        progress_layout.addWidget(self.progress_label)
        progress_layout.addStretch()
        progress_layout.addWidget(self.progress_show_radio)
        progress_layout.addWidget(self.progress_hide_radio)
        layout.addWidget(self.progress_row)

        self.progress_divider = HDividerLine()
        layout.addWidget(self.progress_divider)

        sequence_title_row = QHBoxLayout()
        sequence_title_row.setContentsMargins(0, 0, 0, 0)
        sequence_title_row.setSpacing(16)
        self.sequence_label = QLabel("Blink sequence")
        self.sequence_label.setObjectName("settingSubSectionTitle")
        self.add_step_btn = QPushButton("Add step")
        self.add_step_btn.setObjectName("settingNormalButton")
        self.add_step_btn.setFixedSize(160, 30)
        sequence_title_row.addWidget(self.sequence_label)
        sequence_title_row.addStretch()
        sequence_title_row.addWidget(self.add_step_btn)
        layout.addLayout(sequence_title_row)

        self.sequence_host = QWidget()
        self.sequence_layout = QVBoxLayout(self.sequence_host)
        self.sequence_layout.setContentsMargins(0, 0, 0, 0)
        self.sequence_layout.setSpacing(8)
        layout.addWidget(self.sequence_host)

        self.sequence_divider = HDividerLine()
        layout.addWidget(self.sequence_divider)

        self.audio_switch_row = QWidget()
        audio_switch_layout = QHBoxLayout(self.audio_switch_row)
        audio_switch_layout.setContentsMargins(0, 0, 0, 0)
        audio_switch_layout.setSpacing(16)
        self.audio_switch_label = QLabel("Play audio on call")
        self.audio_switch_label.setObjectName("settingSubSectionTitle")
        self.audio_on_radio = QRadioButton("On")
        self.audio_off_radio = QRadioButton("Off")
        audio_switch_layout.addWidget(self.audio_switch_label)
        audio_switch_layout.addStretch()
        audio_switch_layout.addWidget(self.audio_on_radio)
        audio_switch_layout.addWidget(self.audio_off_radio)
        layout.addWidget(self.audio_switch_row)

        self.audio_switch_divider = HDividerLine()
        layout.addWidget(self.audio_switch_divider)

        self.audio_file_row = QWidget()
        audio_file_layout = QHBoxLayout(self.audio_file_row)
        audio_file_layout.setContentsMargins(0, 0, 0, 0)
        audio_file_layout.setSpacing(12)
        self.audio_file_label = QLabel("Audio file")
        self.audio_file_label.setObjectName("settingSubSectionTitle")
        self.audio_file_combo = QComboBox()
        self.audio_file_combo.setFixedSize(140, 40)
        self.audio_preview_btn = QPushButton("Preview")
        self.audio_preview_btn.setObjectName("settingNormalButton")
        self.audio_preview_btn.setFixedSize(160, 30)
        audio_file_layout.addWidget(self.audio_file_label)
        audio_file_layout.addStretch()
        audio_file_layout.addWidget(self.audio_file_combo)
        audio_file_layout.addWidget(self.audio_preview_btn)
        layout.addWidget(self.audio_file_row)

        self.audio_file_divider = HDividerLine()
        layout.addWidget(self.audio_file_divider)

        self.audio_volume_row = QWidget()
        audio_volume_layout = QHBoxLayout(self.audio_volume_row)
        audio_volume_layout.setContentsMargins(0, 0, 0, 0)
        audio_volume_layout.setSpacing(12)
        self.audio_volume_label = QLabel("Audio volume")
        self.audio_volume_label.setObjectName("settingSubSectionTitle")
        self.audio_volume_slider = QSlider(Qt.Orientation.Horizontal)
        self.audio_volume_slider.setRange(0, 100)
        self.audio_volume_slider.setSingleStep(1)
        self.audio_volume_slider.setPageStep(5)
        self.audio_volume_slider.setFixedWidth(220)
        self.audio_volume_value_label = QLabel("100%")
        self.audio_volume_value_label.setFixedWidth(52)
        audio_volume_layout.addWidget(self.audio_volume_label)
        audio_volume_layout.addStretch()
        audio_volume_layout.addWidget(self.audio_volume_slider)
        audio_volume_layout.addWidget(self.audio_volume_value_label)
        layout.addWidget(self.audio_volume_row)

        self.audio_volume_divider = HDividerLine()
        layout.addWidget(self.audio_volume_divider)

        self.audio_duration_row = QWidget()
        audio_duration_layout = QHBoxLayout(self.audio_duration_row)
        audio_duration_layout.setContentsMargins(0, 0, 0, 0)
        audio_duration_layout.setSpacing(12)
        self.audio_duration_label = QLabel("Audio play duration")
        self.audio_duration_label.setObjectName("settingSubSectionTitle")
        self.audio_duration_combo = QComboBox()
        self.audio_duration_combo.setFixedSize(140, 40)
        audio_duration_layout.addWidget(self.audio_duration_label)
        audio_duration_layout.addStretch()
        audio_duration_layout.addWidget(self.audio_duration_combo)
        layout.addWidget(self.audio_duration_row)

        self.audio_duration_divider = HDividerLine()
        layout.addWidget(self.audio_duration_divider)

        self.abnormal_alert_row = QWidget()
        abnormal_alert_layout = QHBoxLayout(self.abnormal_alert_row)
        abnormal_alert_layout.setContentsMargins(0, 0, 0, 0)
        abnormal_alert_layout.setSpacing(16)
        self.abnormal_alert_label = QLabel("Automatic abnormality alert")
        self.abnormal_alert_label.setObjectName("settingSubSectionTitle")
        self.abnormal_alert_on_radio = QRadioButton("On")
        self.abnormal_alert_off_radio = QRadioButton("Off")
        abnormal_alert_layout.addWidget(self.abnormal_alert_label)
        abnormal_alert_layout.addStretch()
        abnormal_alert_layout.addWidget(self.abnormal_alert_on_radio)
        abnormal_alert_layout.addWidget(self.abnormal_alert_off_radio)
        layout.addWidget(self.abnormal_alert_row)

        self.abnormal_alert_divider = HDividerLine()
        layout.addWidget(self.abnormal_alert_divider)

        self.camera_missing_duration_row = QWidget()
        camera_missing_layout = QHBoxLayout(self.camera_missing_duration_row)
        camera_missing_layout.setContentsMargins(0, 0, 0, 0)
        camera_missing_layout.setSpacing(12)
        self.camera_missing_duration_label = QLabel("Camera unavailable for")
        self.camera_missing_duration_label.setObjectName("settingSubSectionTitle")
        self.camera_missing_duration_combo = QComboBox()
        self.camera_missing_duration_combo.setFixedSize(140, 40)
        camera_missing_layout.addWidget(self.camera_missing_duration_label)
        camera_missing_layout.addStretch()
        camera_missing_layout.addWidget(self.camera_missing_duration_combo)
        layout.addWidget(self.camera_missing_duration_row)

        self.face_missing_duration_row = QWidget()
        face_missing_layout = QHBoxLayout(self.face_missing_duration_row)
        face_missing_layout.setContentsMargins(0, 0, 0, 0)
        face_missing_layout.setSpacing(12)
        self.face_missing_duration_label = QLabel("Face not detected for")
        self.face_missing_duration_label.setObjectName("settingSubSectionTitle")
        self.face_missing_duration_combo = QComboBox()
        self.face_missing_duration_combo.setFixedSize(140, 40)
        face_missing_layout.addWidget(self.face_missing_duration_label)
        face_missing_layout.addStretch()
        face_missing_layout.addWidget(self.face_missing_duration_combo)
        layout.addWidget(self.face_missing_duration_row)

        self.abnormal_alert_settings_divider = HDividerLine()
        layout.addWidget(self.abnormal_alert_settings_divider)

        self.model_row = QWidget()
        self.model_row.setObjectName("settingModelFilesRow")
        model_row_layout = QHBoxLayout(self.model_row)
        model_row_layout.setContentsMargins(0, 0, 0, 0)
        model_row_layout.setSpacing(12)

        self.model_label = QLabel("Download/Update model files")
        self.model_label.setObjectName("settingSubSectionTitle")
        self.model_desc_input = QLineEdit("")
        self.model_desc_input.setObjectName("settingModelFilesDesc")
        self.model_desc_input.setReadOnly(True)
        self.model_btn = QPushButton("Download/Update")
        self.model_btn.setObjectName("settingModelFilesBtn")
        self.model_btn.setFixedSize(230, 36)

        model_row_layout.addWidget(self.model_label)
        model_row_layout.addWidget(self.model_desc_input, 1)
        model_row_layout.addWidget(self.model_btn)
        layout.addWidget(self.model_row)

        self.model_divider = HDividerLine()
        layout.addWidget(self.model_divider)
        layout.addStretch()
